Class {
	#name : #'MyProjectClassC_B',
	#superclass : #Object,
	#instVars : [
		'lfjpbgmovwzfn',
		'fsfctacgjt',
		'xdlocvudyzlgum',
		'likyveqvk',
		'nlouwquope',
		'pnyityuoekk',
		'zsoigqrciqlshh',
		'ufvrmjrmqgectj',
		'fbaynb',
		'ymlgxtlsqyaps',
		'pzyqqtc',
		'wmhjdwhpxyc',
		'fkhzgkkd',
		'gqganzkmys',
		'sxlshhd',
		'fpuomrc'
	],
	#category : #'MyProject-C'
}

{ #category : #'scrollpane-scrolling' }
MyProjectClassC_B >> alztlvaxAJ [
	^ zsoigqrciqlshh
]

{ #category : #preparation }
MyProjectClassC_B >> alztlvaxAX [
	^ #uxxejsluykwhjguhlfxvxkffkjgtfkjhzx
]

{ #category : #'tests - options' }
MyProjectClassC_B >> alztlvaxS [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do ei."
	^ #ezhzxbfskfqjncaljushgyqcia
]

{ #category : #utilities }
MyProjectClassC_B >> arcojmihvF [
	^ ymlgxtlsqyaps
]

{ #category : #'testing - geometry' }
MyProjectClassC_B >> bsqxhbdyAT [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad mi."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Aliquip reprehe.'
]

{ #category : #'tests-manual' }
MyProjectClassC_B >> bsqxhbdyY [
	^ #jehisrtkroynpapebsgxqfwzxsfbgkvxqfnqkpcjlxscgshzhf
]

{ #category : #'file list' }
MyProjectClassC_B >> cbaovvH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing el."
	^ wmhjdwhpxyc
]

{ #category : #setup }
MyProjectClassC_B >> dinutmuumuunrwAW [
	^ #[9 165 173 6 32 211 19 153 36 102 204 188 117 157 59 160 166 114 73 38 208 5 11 233 157 1 169 82 32 58 78 226 173 214 246 32 253 62 85 4 245 65 253 61 156 235 166 156 39 249 106 88 196 229 68 24 58 219 151 124 174 119 44 106 228 217 215 105 136 108 239 32 129 44 171 218 207 166 253 60 72 166 62 134 149 147 196 162 132 95 70 41 108 141 67 195 7 198 139 54 187 71 89 163 80 38 162 238 17 126 95 94 131 57 61 57 143 34 176 200 17 21 143 28 208 38 131 100 177]
]

{ #category : #'primitives-access' }
MyProjectClassC_B >> dspygltysjzuwbO [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, se."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .'
]

{ #category : #building }
MyProjectClassC_B >> evtbgkvtAM [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Velit magna non pariatur incididunt anim proident nulla. Laboris non ut minim. 

Commodo sed. Ullamco id non consectetur in adipiscing dolor. Ad tempor ex incididunt commodo quis dolor qui anim minim ut velit do deserunt reprehenderit officia eu voluptate ullamco minim. Ut excepteur minim pariatur duis consectetur magna lorem ut ut nulla quis aliqua non commodo enim tempor lorem minim id amet. Voluptate nisi ullamco in occaecat.'
]

{ #category : #'tests-marker' }
MyProjectClassC_B >> evtbgkvtW [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do."
	^ #sihmtsyjlyfijrhwjtaiavwenwtpxxbtuxlaxgvtl
]

{ #category : #'menu - operations' }
MyProjectClassC_B >> fvbgrqerzbchAR [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex."
	^ #gpgxjoawrhwudfijqwczcjbsxnokvze
]

{ #category : #'wrapped protocol' }
MyProjectClassC_B >> htwkaucmdflacB [
	^ #[3 83 14 93 33 65 114 127 74 230 81 15 7 119 129 29 132 53 163 170 24 144 163 80 93 9 186 107 253 97 11 167 12 113 106 36 103 197 109 75 16 255 43 202 102 168 108 33 225 122 166 175 23 178 193 150 21 126 242 145 39 65 45 239 163 45 25 203 227 15 130 116 30 137 147 24 92 94 123 202 80 183 198 86 41 116 72 214 230 197 191 143 32 46 163 96 150 38 51 103 89 236 77 235 15 112 155 184 240 31 234 13 170 38 188 25 34 208 199 209 71 62 130 149 74 254 215 248 131 219 88 252 17 137 37 231 241 27 241 22 189 147 206 51 221 54 139 185 18 174]
]

{ #category : #menu }
MyProjectClassC_B >> htwkaucmdflacE [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididu."
	^ #elpwchvrccvqyvbymoxgnteveabyvycxdqnugchfckquulqkqjdx
]

{ #category : #'parsing-large int' }
MyProjectClassC_B >> kbhkrzeidygxvaAL [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ve."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Ex dolore culpa occaecat labore officia adipiscing ut velit cupidatat labore nisi est officia veniam. Consequat et consectetur eu. Ut mollit exercitation voluptate non qui quis consectetur exercitation dolore enim do qui minim adipiscing. Incididunt eiusmod commodo ad labore labore exercitation ut. Cupidatat est culpa ea aliqua ullamco nostrud anim quis laboris est duis. In lorem fugiat est exercitation ullamco deserunt nulla. Mollit et culpa adipisc.'
]

{ #category : #'view creating' }
MyProjectClassC_B >> kcjtrcfiarjmzhaAS [
	"Lorem ipsum dolor sit amet, consectetur ad."
	^ #miahncxnslxhbqkfjwdwn
]

{ #category : #'test shadowing' }
MyProjectClassC_B >> kcjtrcfiarjmzhaU [
	^ #[18 187 242 106 135 240 224 239 228 49 167 207 97 152 169 73 186 211 123 185 143 254 161 140 226 234 127 74 212 196 137 96 254 247 236 25 21 161 243 98 26 213 186 10 131 12 18 203 243 44 180 155 109 250 196 70 193 214 72 240 200 31 153 120 188 56 207 171 162 185 189 84 19 246 110 28 212 170 211 203 192 244 240 116 123 16 65 50 115 47 152 86 143 174 234 95 131 217 30]
]

{ #category : #dispatching }
MyProjectClassC_B >> kwlglygmmluajbxAC [
	^ pzyqqtc
]

{ #category : #'api-errors' }
MyProjectClassC_B >> lfmnzhdjdgBC [
	^ #[111 18 74 53 98 6 31 106 143 167 95 14 180 34 36 230 122 251 99 141 5 77 137 135 25 186 191 172 117 212 161 112 2 148 134 13 220 233 4 54 102 177 82 79 25 145 138 207 211 167 2 165 43 16 66 136 127 71 168 113 83 161 20 178 230 148 82 104 169 164 114 229 80 134 24 138 12 161 77 8 218 97 74 164 125 118 160 203 100 217 199 231 19 28 182 61 253 77 234 237 113 179 235 231 232 220 148 29 213 219 74 45 61 122 56 54 10 102 197 129 200 2 221 23 205 252 108 111 241 215 228 84 222 54 229 204 16 98 218 53 246 237 89 66 66 92 16 86 73 16]
]

{ #category : #installation }
MyProjectClassC_B >> lkdmskklqkzqgfX [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nost."
	^ ymlgxtlsqyaps
]

{ #category : #'border-styles' }
MyProjectClassC_B >> moieqfvAH [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim v."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Voluptate non sunt cillum in minim dolor reprehenderit quis deserunt aliquip fugiat nostrud tempor. Commodo aliqua dolor incididunt excepteur in qui nulla eu dolor ex amet nulla labore ut irure minim labore ut consequat. Laboris sed commodo culpa dolor consequat ut in irure pariatur culpa aliquip occaecat tempor ad irure sunt magna. Pariatur laboris mollit sit.'
]

{ #category : #'string morph' }
MyProjectClassC_B >> moieqfvL [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut ."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor.'
]

{ #category : #'selection-classes' }
MyProjectClassC_B >> mrrnqsifzyAZ [
	^ pzyqqtc
]

{ #category : #'stamp values' }
MyProjectClassC_B >> mrrnqsifzyBA [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Et est ex. Consectetur anim esse exercitation nulla reprehenderit eiusmod incididunt mollit dolor proident. Sed ullamco magna sed occaecat est id duis ut labore. Ut voluptate dolor amet velit officia. Ullamco qui. 

Dolor ex culpa proident in lorem ut fugiat consectetur proident eiusmod pariatur ut cillum officia reprehen.'
]

{ #category : #'tests-numbers' }
MyProjectClassC_B >> nennewsgdkrqmuBB [
	^ #tvspkjaqdtdkymfhrvkkutrwhdk
]

{ #category : #'accessing - bad' }
MyProjectClassC_B >> ojdbxkvvxhxtteAU [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut en."
	^ #[150 131 250 8 71 236 221 20 76 244 149 198 135 135 218 161 47 138 226 158 181 69 3 209 67 190 190 41 27 245 69 204 196 152 205 139 109 55 114 72 119 166 105 54 183 213 25 62 25 94 214 37 138 215 183 27 177 70 88 206 47 107 230 121 130 210 181 207 175 95 10 164 102 99 137 38 216 59 60 145 193 61 89 152 166 9 12 114 231 64 209 253 21 199 151]
]

{ #category : #'tests object' }
MyProjectClassC_B >> ounnvbjsgswuzegAN [
	^ nlouwquope
]

{ #category : #'visiting - two fingers gestures' }
MyProjectClassC_B >> ounnvbjsgswuzegK [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ."
	^ #[42 30 102 138 32 95 235 221 161 201 40 217 189 188 62 238 67 92 176 102 134 153 254 226 134 250 249 110 133 93 186 88 49 128 31 121 19 19 58 64]
]

{ #category : #'properties-setting' }
MyProjectClassC_B >> ounnvbjsgswuzegT [
	^ #[60 72 209 177 218 235 156 89 178 202 29 131 44 109 204 148 245 41 111 21 221 3 189 5 97 119 247 255 47]
]

{ #category : #'scrollpane-brick-creation' }
MyProjectClassC_B >> pjkxsrbvR [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum do.'
]

{ #category : #'private dispatch' }
MyProjectClassC_B >> pzxiyayaqdrsvsAA [
	^ #[143 114 21 99 185 146 102 129 115 234 146 26 200 181 166 97 228 251 42 99 96 194 147 211 209 130 198 241 125 58 36 192 8 189 47 13 120 31 160 84 32 73 58 135 155 191 224 41 94 91 181 247 19 172 149 240 11 33 105 82 172 163 208 64 172 116 108 132 146 47 146 80 61 180 106 72 254 250 122 111 175 104 164 227 128 74 5 6 211 225 188 45 208 140 61 181 33 84 149 232 106 95 62 88 67 200 187 239 44 84 13 66 81 21 208 35 221 177 197 204 22 252 33 84 83 14 2 30 63 149 80 116 26 184 133 68 35 1 122 62 5 102 254 237 89 255]
]

{ #category : #defaults }
MyProjectClassC_B >> pzxiyayaqdrsvsAD [
	"Lorem ipsum dolor sit amet, con."
	^ #kvibduluosfezfqwyipnkozbtnmrkkcvxip
]

{ #category : #'linked frames' }
MyProjectClassC_B >> pzxiyayaqdrsvsAI [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim.'
]

{ #category : #'private - sourcepointer conversion' }
MyProjectClassC_B >> pzxiyayaqdrsvsAK [
	^ fkhzgkkd
]

{ #category : #obsolete }
MyProjectClassC_B >> qujrdwAG [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate .'
]

{ #category : #'scope creation' }
MyProjectClassC_B >> rbjdbdbiglJ [
	^ #uaieborbodmfrsvdnwnvgzgaglezzwijbboqyxgqoxeasoecdty
]

{ #category : #scopes }
MyProjectClassC_B >> rbjdbdbiglQ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad."
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Ea elit voluptate non pariatur et in exercitation. Minim nisi ut non excepteur sit non ea consectetur velit ullamco dolore proident et in eu ex velit mollit. Duis minim in irure culpa sunt consequat reprehenderit cupidatat voluptate qui aliqua ea aliqua culpa tempor ea irur.'
]

{ #category : #'to move to a simple RPackage test case' }
MyProjectClassC_B >> rnmvscafmpphjcG [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed ."
	^ #rjxelanqjpq
]

{ #category : #dragging }
MyProjectClassC_B >> umahednreAP [
	^ #[172 145 21 3 123 227 116 37 248 248 104 111 164 113 117 246 54 97 245 184 84 147 249 238 27 51 56 9 186 237 89 169 92 230 69 126 147 239 129 203 93 51 106 101 5 23 215 187 62 180 196 213 180 137 139 38 90 38 217 171 73 30 181 104 214 133 188 58 89 238 220 15 135 203 215 127 15 143 17 177 216 188 153 212 159 230 33 173 158 68 134 200 41 88 90 111 119 10 64 111 49 225 198 132 140 55 189 101 201 18 151 185 185 178 27 175 27 83 55 1 170 22 168 253 145 234 55 249 126 194 107 227 207]
]

{ #category : #'keymaps - window tiling' }
MyProjectClassC_B >> umahednreV [
	^ 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. .'
]

{ #category : #'drag\'n\'drop' }
MyProjectClassC_B >> uqsudtA [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitatio."
	^ wmhjdwhpxyc
]

{ #category : #'ui process' }
MyProjectClassC_B >> vlzdtkzM [
	^ #[33 149 191 43 100 129 35 45 27 98 110 211 162 18 185 105 31 51 113 240 219 96 144 230 91 172 186 179 20 105 59 78 162 140 209 133 197 91 172 232 241 105 89 165 43 239 231 239 128 241 41 159 111 237 32 174 252 217 208 69 32 199 111 156 171 76 147 31 229 252 70 122 251 140 68]
]

{ #category : #morphic }
MyProjectClassC_B >> wcrvoecqviovAQ [
	^ #[66 129 1 107 243 148 64 194 164 237 54 144 83 84 183 59 215 59 163 174 128 115 61 129 178 4 160 126 58 215 248 19 82 157 14 169 205 159 89 120 246 141 210 157 148 151 109 229 42 4 132 87 246 16 207 19 101 203 115 58 214 11 97 74 17 18 238 6 76 230 64 168 164 140 236 226 157 201 228 159]
]

{ #category : #'API-changes' }
MyProjectClassC_B >> wcrvoecqviovAV [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad."
	^ #[79 138 210 46 115 73 229 252 234 2 12 15 62 11 102 99 154 141 131 242 168 105 104 245 225 17 254 220 81 209 196 246 79 206 1 127 50 255 108 90 172 55 60 14 210 98 224 230 208 87 215 110 228 38 123 123 137 104 82 179 193 36 126 106 89 201 173 114 132]
]

{ #category : #'tests - basic' }
MyProjectClassC_B >> wcrvoecqviovAY [
	^ #[238 125 99 179 201 23 195 78 146 45 235 173 32 33 102 203 209 98 199 236 121 77 103 133 213 140 181 246 123 172 57 5 251 149 124 100 124 193 15 153 93 43 141 69 198 233 82 57 71 71 246 89 33 2 114 149 181 213 153 234 52 155 252 64 164 186 77 101 226 233 24 191 245 205 209 88 41 5 27 7 228 152 8 59 80 231 143 84 145]
]

{ #category : #'tests-bestNodeIn' }
MyProjectClassC_B >> wcrvoecqviovD [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nos."
	^ sxlshhd
]

{ #category : #'public API' }
MyProjectClassC_B >> wqpyhxxeeajhbAO [
	^ pnyityuoekk
]

{ #category : #ranges }
MyProjectClassC_B >> wqpyhxxeeajhbI [
	^ sxlshhd
]

{ #category : #'trait1 - c' }
MyProjectClassC_B >> wqpyhxxeeajhbN [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et ."
	^ fkhzgkkd
]

{ #category : #'accessing segments' }
MyProjectClassC_B >> wtexgayqbeeAF [
	^ #[95 182 25 239 229 249 33 68 32 69 57 5 242 141 153 3 9 136 32 25 71 127 79 169 237 111 89 224 190 77 141 102 183 122 88 57 192 125 239 72 50 234 126 4 245 84 209 95 188 128 139 214 249 234 190 38 185 80 69 243 231 165 193 1 217 178 106 83 221 130 22 79 9 56 179 216 130 161 251 51 98 235 20 7 165 207 39 221 224 53 95 191 218 121 163 12 162 127 99 71 97 238 180 180 70 124 147 28 104 57 3 159 126 107 178 197 222 194 56 247 51 38 255 217 92 10 252 37 213 24 182 96 170 132 54 195 218 45 128 144 103 137 189 191 247 212 65 20 28 31 48 58 165 147 192 232 177 1 249 182 23 167 226 180 132 43 29 235 35 136 208 18 38 154 159 209 108 48 193 129 190 202 239 252 163 231 167 6 200 218 20 50 26 106 183]
]

{ #category : #'brick-tab-label-testing' }
MyProjectClassC_B >> yhudfoffC [
	"Lorem ipsum dolor sit amet, co."
	^ ymlgxtlsqyaps
]

{ #category : #'api-valueHolder' }
MyProjectClassC_B >> ymnkriwyhzyleAB [
	^ gqganzkmys
]

{ #category : #'private-creation' }
MyProjectClassC_B >> ymnkriwyhzyleAE [
	^ #[164 125 139 73 122 219 239 154 128 39 171 234 238 233 140 237 1 170 91 185]
]

{ #category : #'api-compatibility' }
MyProjectClassC_B >> yytnlzzyvrP [
	"Lorem ipsum dolor sit amet, consectetur adipiscing e."
	^ xdlocvudyzlgum
]

{ #category : #api }
MyProjectClassC_B >> zuawlpugdlZ [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi u."
	^ #[3 87 58 252 118 69 167 29 125 162 161 35 128 152 216 134 67 212 144 168 129 36 143 248 255 107 60 84 213 236 239 36 234 169 141 113 21 208 225 254 240 221 254 117 112 47 7 185 98 198 49 2 199 206 250 156 217 93 218 55 126 240 71 175 138 107 118 239 53 202 131 39 226 62 104 222 12 111 99 13 236 30 32 170 107 209 46 248 211 62 41 239 67 35 190 40 247 91 76 2 63 136 175 193 111 189]
]
